version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_ai_project
    restart: always
    environment:
      POSTGRES_DB: db-ai-cliee
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
